#!/bin/sh

ssh grenache.rcbowen.com "cd /var/www/vhosts/boxofclue/presentations && git pull"

scp -r /home/rbowen/devel/redhat/project-presos/rdo/presentations/rdo_overview grenache.rcbowen.com:/var/www/vhosts/boxofclue/presentations/
scp -r /home/rbowen/devel/redhat/project-presos/rdo/presentations/openstack grenache.rcbowen.com:/var/www/vhosts/boxofclue/presentations/
